name: Daily Flight Price Scraper

on:
  workflow_dispatch:   # leidžia rankinį paleidimą per “Run workflow” mygtuką
  schedule:
    - cron: '0 9 * * *'  # kasdien 09:00 UTC (11:00 CET)

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Commit updated CSV
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-update flight price on ${{ github.event.schedule || github.event.workflow_dispatch }}"
          file_pattern: prices.csv
