name: Daily Flight Price Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install deps
        run: pip install requests

      - name: Run scraper
        run: python scraper.py

      - name: Commit CSV
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-update flight price"
          file_pattern: prices.csv
